version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.1
    - 4.0.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
  - dependency-name: sass-loader
    versions:
    - 10.1.1
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongodb
    versions:
    - 3.6.5
  - dependency-name: socket.io
    versions:
    - 3.1.1
    - 4.0.0
